var productos = [
  {
    "Producto": "Papas fritas",
    "Marca": "Papitas",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 282,
    "Tamaño (g/ml)": 240,
    "Porción (g/ml)": 25,
    "Porciones por envase": 9.6,
    "Grasa saturada (cal)": 33.75,
    "Otras grasas (cal)": 37.5,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 114.58333333333334,
    "Energía por porción (cal)": 128.33333333333334,
    "Energía por envase (cal)": 1232,
    "Filename": "papas-fritas",
    "Escala": 0.6,
    "ExCalorias": true,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": true,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Papas fritas con queso",
    "Marca": "Rules",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 235,
    "Tamaño (g/ml)": 290,
    "Porción (g/ml)": 25,
    "Porciones por envase": 11.6,
    "Grasa saturada (cal)": 30,
    "Otras grasas (cal)": 16.551724137931036,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 146.55172413793105,
    "Energía por porción (cal)": 120.43103448275862,
    "Energía por envase (cal)": 1397,
    "Filename": "papas-queso",
    "Escala": 0.65,
    "ExCalorias": true,
    "ExGrasasSat": true,
    "ExGrasasTrans": false,
    "ExSodio": true,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Galletas",
    "Marca": "Orale",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 142,
    "Tamaño (g/ml)": 114,
    "Porción (g/ml)": 30,
    "Porciones por envase": 3.8,
    "Grasa saturada (cal)": 14,
    "Otras grasas (cal)": 39,
    "Azúcares (cal)": 48,
    "Sodio (mg)": 114,
    "Energía por porción (cal)": 142,
    "Energía por envase (cal)": 549,
    "Filename": "galletas",
    "Escala": 0.6,
    "ExCalorias": true,
    "ExGrasasSat": true,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": true,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Galletas con chispas",
    "Marca": "Cookies",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 141,
    "Tamaño (g/ml)": 114,
    "Porción (g/ml)": 30,
    "Porciones por envase": 3.8,
    "Grasa saturada (cal)": 33,
    "Otras grasas (cal)": 20,
    "Azúcares (cal)": 41,
    "Sodio (mg)": 76,
    "Energía por porción (cal)": 141,
    "Energía por envase (cal)": 536,
    "Filename": "galletas-chispas",
    "Escala": 0.75,
    "ExCalorias": true,
    "ExGrasasSat": true,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": true,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Barra de chocolate",
    "Marca": "Church",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 208,
    "Tamaño (g/ml)": 40,
    "Porción (g/ml)": 40,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 60.7,
    "Otras grasas (cal)": 41.3,
    "Azúcares (cal)": 84,
    "Sodio (mg)": 76,
    "Energía por porción (cal)": 208,
    "Energía por envase (cal)": 208,
    "Filename": "barra-chocolate",
    "Escala": 0.9,
    "ExCalorias": true,
    "ExGrasasSat": true,
    "ExGrasasTrans": false,
    "ExSodio": true,
    "ExAzucares": true,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Chocolate en polvo",
    "Marca": "Choco Miaw",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 132,
    "Tamaño (g/ml)": 350,
    "Porción (g/ml)": 17,
    "Porciones por envase": 20.58823529411765,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 104,
    "Sodio (mg)": 134,
    "Energía por porción (cal)": 146.3942857142857,
    "Energía por envase (cal)": 3014,
    "Filename": "chocolate-polvo",
    "Escala": 0.7,
    "ExCalorias": true,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": true,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Atún",
    "Marca": "Ramones",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 110,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0.9,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 239,
    "Energía por porción (cal)": 109,
    "Energía por envase (cal)": 109,
    "Filename": "atun",
    "Escala": 0.85,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Jamón enlatado",
    "Marca": "Wham",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 310,
    "Tamaño (g/ml)": 198,
    "Porción (g/ml)": 99,
    "Porciones por envase": 2,
    "Grasa saturada (cal)": 45,
    "Otras grasas (cal)": 76.5,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 345,
    "Energía por porción (cal)": 308,
    "Energía por envase (cal)": 616,
    "Filename": "jamon-enlatado",
    "Escala": 0.85,
    "ExCalorias": true,
    "ExGrasasSat": true,
    "ExGrasasTrans": true,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Frijoles",
    "Marca": "Ricadora",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 124.6,
    "Tamaño (g/ml)": 580,
    "Porción (g/ml)": 50,
    "Porciones por envase": 11.6,
    "Grasa saturada (cal)": 9,
    "Otras grasas (cal)": 18,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 221,
    "Energía por porción (cal)": 46.98275862068966,
    "Energía por envase (cal)": 545,
    "Filename": "frijoles",
    "Escala": 0.75,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Mayonesa",
    "Marca": "Love",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 40,
    "Tamaño (g/ml)": 190,
    "Porción (g/ml)": 10,
    "Porciones por envase": 19,
    "Grasa saturada (cal)": 6.3,
    "Otras grasas (cal)": 31.5,
    "Azúcares (cal)": 2,
    "Sodio (mg)": 73,
    "Energía por porción (cal)": 35.31578947368421,
    "Energía por envase (cal)": 671,
    "Filename": "mayonesa",
    "Escala": 0.85,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Catsup",
    "Marca": "Enrique",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 32,
    "Tamaño (g/ml)": 650,
    "Porción (g/ml)": 30,
    "Porciones por envase": 21.666666666666668,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 28,
    "Sodio (mg)": 260,
    "Energía por porción (cal)": 31.98461538461538,
    "Energía por envase (cal)": 693,
    "Filename": "catsup",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": true,
    "ExAzucares": true,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Carne para hamburguesas",
    "Marca": "Karnuka",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 286,
    "Tamaño (g/ml)": 904,
    "Porción (g/ml)": 113,
    "Porciones por envase": 8,
    "Grasa saturada (cal)": 81,
    "Otras grasas (cal)": 117,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 550,
    "Energía por porción (cal)": 286,
    "Energía por envase (cal)": 2288,
    "Filename": "carne-hamburguesas",
    "Escala": 0.85,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Sándwich",
    "Marca": "Chanwich",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 400,
    "Tamaño (g/ml)": 89,
    "Porción (g/ml)": 89,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 18,
    "Otras grasas (cal)": 27,
    "Azúcares (cal)": 16,
    "Sodio (mg)": 680,
    "Energía por porción (cal)": 193,
    "Energía por envase (cal)": 193,
    "Filename": "sandwich",
    "Escala": 0.85,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Refresco",
    "Marca": "Rock-Cola",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 60,
    "Tamaño (g/ml)": 600,
    "Porción (g/ml)": 600,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 252,
    "Sodio (mg)": 60,
    "Energía por porción (cal)": 252,
    "Energía por envase (cal)": 252,
    "Filename": "refresco",
    "Escala": 0.55,
    "ExCalorias": true,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": true,
    "ContEdulcorantes": true,
    "ContCafeina": false
  },
  {
    "Producto": "Refresco",
    "Marca": "Rock-Cola",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 71,
    "Tamaño (g/ml)": 355,
    "Porción (g/ml)": 355,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 71,
    "Sodio (mg)": 24,
    "Energía por porción (cal)": 71,
    "Energía por envase (cal)": 71,
    "Filename": "refresco-lata",
    "Escala": 0.95,
    "ExCalorias": true,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": true,
    "ContEdulcorantes": true,
    "ContCafeina": false
  },
  {
    "Producto": "Refresco",
    "Marca": "Rock-Cola Light",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 0,
    "Tamaño (g/ml)": 355,
    "Porción (g/ml)": 355,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 24,
    "Energía por porción (cal)": 0,
    "Energía por envase (cal)": 0,
    "Filename": "refresco-lata-light",
    "Escala": 0.95,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": true
  },
  {
    "Producto": "Refresco",
    "Marca": "Refresca",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 126.9,
    "Tamaño (g/ml)": 355,
    "Porción (g/ml)": 355,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 33.5,
    "Sodio (mg)": 86.2,
    "Energía por porción (cal)": 126.9,
    "Energía por envase (cal)": 126.9,
    "Filename": "refresco-toronja",
    "Escala": 0.95,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Jugo",
    "Marca": "Jutec Fresco",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 84,
    "Tamaño (g/ml)": 600,
    "Porción (g/ml)": 600,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 115,
    "Sodio (mg)": 159,
    "Energía por porción (cal)": 115,
    "Energía por envase (cal)": 115,
    "Filename": "jugo",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Agua",
    "Marca": "WaTec",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 0,
    "Tamaño (g/ml)": 600,
    "Porción (g/ml)": 600,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 0,
    "Energía por porción (cal)": 0,
    "Energía por envase (cal)": 0,
    "Filename": "agua",
    "Escala": 0.5,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Aguacate",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 160,
    "Tamaño (g/ml)": 150,
    "Porción (g/ml)": 50,
    "Porciones por envase": 3,
    "Grasa saturada (cal)": 9,
    "Otras grasas (cal)": 20,
    "Azúcares (cal)": 36,
    "Sodio (mg)": 0,
    "Energía por porción (cal)": 26.666666666666668,
    "Energía por envase (cal)": 80,
    "Filename": "aguacate",
    "Escala": 0.7,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Tomate",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 20,
    "Tamaño (g/ml)": 400,
    "Porción (g/ml)": 100,
    "Porciones por envase": 4,
    "Grasa saturada (cal)": 9,
    "Otras grasas (cal)": 1.8,
    "Azúcares (cal)": 12,
    "Sodio (mg)": 9,
    "Energía por porción (cal)": 18,
    "Energía por envase (cal)": 72,
    "Filename": "tomate",
    "Escala": 0.9,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Plátano",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 48,
    "Tamaño (g/ml)": 120,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1.2,
    "Grasa saturada (cal)": 1,
    "Otras grasas (cal)": 1.8,
    "Azúcares (cal)": 92,
    "Sodio (mg)": 1,
    "Energía por porción (cal)": 74.16666666666667,
    "Energía por envase (cal)": 89,
    "Filename": "platano",
    "Escala": 0.75,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Manzana",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 42,
    "Tamaño (g/ml)": 154,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1.54,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0.2,
    "Azúcares (cal)": 56,
    "Sodio (mg)": 1,
    "Energía por porción (cal)": 33.76623376623377,
    "Energía por envase (cal)": 52,
    "Filename": "manzana",
    "Escala": 0.95,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Papaya",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 55,
    "Tamaño (g/ml)": 1000,
    "Porción (g/ml)": 145,
    "Porciones por envase": 6.896551724137931,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 3.6,
    "Azúcares (cal)": 64,
    "Sodio (mg)": 12,
    "Energía por porción (cal)": 8.99,
    "Energía por envase (cal)": 62,
    "Filename": "papaya",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Pera",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 47,
    "Tamaño (g/ml)": 178,
    "Porción (g/ml)": 178,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 2.7,
    "Azúcares (cal)": 53.2,
    "Sodio (mg)": 1.8,
    "Energía por porción (cal)": 101,
    "Energía por envase (cal)": 101,
    "Filename": "pera",
    "Escala": 0.7,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Sandía",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 60,
    "Tamaño (g/ml)": 6000,
    "Porción (g/ml)": 100,
    "Porciones por envase": 60,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 1.8,
    "Azúcares (cal)": 32,
    "Sodio (mg)": 1,
    "Energía por porción (cal)": 0.5,
    "Energía por envase (cal)": 30,
    "Filename": "sandia",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Melón",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 61,
    "Tamaño (g/ml)": 1300,
    "Porción (g/ml)": 100,
    "Porciones por envase": 13,
    "Grasa saturada (cal)": 0.9,
    "Otras grasas (cal)": 0.9,
    "Azúcares (cal)": 32,
    "Sodio (mg)": 16,
    "Energía por porción (cal)": 2.6153846153846154,
    "Energía por envase (cal)": 34,
    "Filename": "melon",
    "Escala": 0.75,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Huevo",
    "Marca": "Bacacho",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 105,
    "Tamaño (g/ml)": 366,
    "Porción (g/ml)": 61,
    "Porciones por envase": 6,
    "Grasa saturada (cal)": 14.4,
    "Otras grasas (cal)": 30.6,
    "Azúcares (cal)": 2.4,
    "Sodio (mg)": 124,
    "Energía por porción (cal)": 78,
    "Energía por envase (cal)": 468,
    "Filename": "huevo",
    "Escala": 0.4,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Pollo",
    "Marca": "Sin hueso",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 357,
    "Tamaño (g/ml)": 600,
    "Porción (g/ml)": 150,
    "Porciones por envase": 4,
    "Grasa saturada (cal)": 50,
    "Otras grasas (cal)": 100,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 122,
    "Energía por porción (cal)": 357.5,
    "Energía por envase (cal)": 1430,
    "Filename": "pollo",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Carne",
    "Marca": "Sirloin",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 745,
    "Tamaño (g/ml)": 306,
    "Porción (g/ml)": 306,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 153,
    "Otras grasas (cal)": 177.3,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 171.4,
    "Energía por porción (cal)": 745,
    "Energía por envase (cal)": 745,
    "Filename": "carne-sirloin",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Carne",
    "Marca": "Milanesa",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 751,
    "Tamaño (g/ml)": 450,
    "Porción (g/ml)": 225,
    "Porciones por envase": 2,
    "Grasa saturada (cal)": 63,
    "Otras grasas (cal)": 78,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 136,
    "Energía por porción (cal)": 375.5,
    "Energía por envase (cal)": 751,
    "Filename": "carne-milanesa",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Salchichas",
    "Marca": "Tipo Viena",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 74,
    "Tamaño (g/ml)": 500,
    "Porción (g/ml)": 45,
    "Porciones por envase": 11.11111111111111,
    "Grasa saturada (cal)": 12,
    "Otras grasas (cal)": 24,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 405,
    "Energía por porción (cal)": 73.35000000000001,
    "Energía por envase (cal)": 815,
    "Filename": "salchichas",
    "Escala": 0.8,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Pan blanco",
    "Marca": "Be my bro",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 65,
    "Tamaño (g/ml)": 460,
    "Porción (g/ml)": 24.2,
    "Porciones por envase": 19.00826446280992,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 105,
    "Energía por porción (cal)": 64.97173913043478,
    "Energía por envase (cal)": 1235,
    "Filename": "pan-blanco",
    "Escala": 0.4,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Pan integral",
    "Marca": "Be my bro",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 77,
    "Tamaño (g/ml)": 680,
    "Porción (g/ml)": 29.6,
    "Porciones por envase": 22.972972972972972,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 6,
    "Azúcares (cal)": 8,
    "Sodio (mg)": 115,
    "Energía por porción (cal)": 77.09058823529412,
    "Energía por envase (cal)": 1771,
    "Filename": "pan-integral",
    "Escala": 0.4,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Pan sin gluten",
    "Marca": "Be my bro",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 70,
    "Tamaño (g/ml)": 430,
    "Porción (g/ml)": 28.67,
    "Porciones por envase": 14.99825601674224,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 18,
    "Azúcares (cal)": 8,
    "Sodio (mg)": 130,
    "Energía por porción (cal)": 70.00813953488372,
    "Energía por envase (cal)": 1050,
    "Filename": "pan-sin-gluten",
    "Escala": 0.4,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Cereal azucarado",
    "Marca": "Sugaritas",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 112,
    "Tamaño (g/ml)": 740,
    "Porción (g/ml)": 30,
    "Porciones por envase": 24.666666666666668,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 48,
    "Sodio (mg)": 115,
    "Energía por porción (cal)": 112.13513513513513,
    "Energía por envase (cal)": 2766,
    "Filename": "cereal-azucarado",
    "Escala": 0.4,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Cereal reducido en azúcar",
    "Marca": "C++",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 104,
    "Tamaño (g/ml)": 450,
    "Porción (g/ml)": 30,
    "Porciones por envase": 15,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 5,
    "Azúcares (cal)": 13,
    "Sodio (mg)": 110.4,
    "Energía por porción (cal)": 103.33333333333333,
    "Energía por envase (cal)": 1550,
    "Filename": "cereal-reducido",
    "Escala": 0.4,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Queso oaxaca",
    "Marca": "Chesito",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 99,
    "Tamaño (g/ml)": 400,
    "Porción (g/ml)": 30,
    "Porciones por envase": 13.333333333333334,
    "Grasa saturada (cal)": 42,
    "Otras grasas (cal)": 25,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 117,
    "Energía por porción (cal)": 98.77499999999999,
    "Energía por envase (cal)": 1317,
    "Filename": "queso-oaxaca",
    "Escala": 0.8,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Queso asadero",
    "Marca": "Chesito",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 94,
    "Tamaño (g/ml)": 400,
    "Porción (g/ml)": 30,
    "Porciones por envase": 13.333333333333334,
    "Grasa saturada (cal)": 35,
    "Otras grasas (cal)": 22,
    "Azúcares (cal)": 6,
    "Sodio (mg)": 147,
    "Energía por porción (cal)": 93.89999999999999,
    "Energía por envase (cal)": 1252,
    "Filename": "queso-asadero",
    "Escala": 0.8,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Queso panela",
    "Marca": "Quesso",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 93,
    "Tamaño (g/ml)": 200,
    "Porción (g/ml)": 30,
    "Porciones por envase": 6.666666666666667,
    "Grasa saturada (cal)": 43,
    "Otras grasas (cal)": 26,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 189,
    "Energía por porción (cal)": 93.45,
    "Energía por envase (cal)": 623,
    "Filename": "queso-panela",
    "Escala": 0.8,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Leche entera",
    "Marca": "Shida",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 154,
    "Tamaño (g/ml)": 1000,
    "Porción (g/ml)": 250,
    "Porciones por envase": 4,
    "Grasa saturada (cal)": 46,
    "Otras grasas (cal)": 29,
    "Azúcares (cal)": 48,
    "Sodio (mg)": 116,
    "Energía por porción (cal)": 154,
    "Energía por envase (cal)": 616,
    "Filename": "leche-entera",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Leche light",
    "Marca": "Shida",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 102,
    "Tamaño (g/ml)": 1000,
    "Porción (g/ml)": 250,
    "Porciones por envase": 4,
    "Grasa saturada (cal)": 14,
    "Otras grasas (cal)": 8,
    "Azúcares (cal)": 48,
    "Sodio (mg)": 116,
    "Energía por porción (cal)": 102,
    "Energía por envase (cal)": 408,
    "Filename": "leche-light",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Leche deslactosada",
    "Marca": "Shida",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 120,
    "Tamaño (g/ml)": 1000,
    "Porción (g/ml)": 250,
    "Porciones por envase": 4,
    "Grasa saturada (cal)": 25,
    "Otras grasas (cal)": 15,
    "Azúcares (cal)": 48,
    "Sodio (mg)": 116,
    "Energía por porción (cal)": 120,
    "Energía por envase (cal)": 480,
    "Filename": "leche-deslactosada",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Leche deslactosada light",
    "Marca": "Shida",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 91,
    "Tamaño (g/ml)": 1000,
    "Porción (g/ml)": 250,
    "Porciones por envase": 4,
    "Grasa saturada (cal)": 7,
    "Otras grasas (cal)": 5,
    "Azúcares (cal)": 48,
    "Sodio (mg)": 116,
    "Energía por porción (cal)": 91,
    "Energía por envase (cal)": 364,
    "Filename": "leche-deslactosada-light",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Leche de almendra",
    "Marca": "Shida",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 21.6,
    "Tamaño (g/ml)": 1000,
    "Porción (g/ml)": 200,
    "Porciones por envase": 5,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 15,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 125,
    "Energía por porción (cal)": 21.6,
    "Energía por envase (cal)": 108,
    "Filename": "leche-almendra",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Tortillas de harina",
    "Marca": "La Rosalía",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 83,
    "Tamaño (g/ml)": 310,
    "Porción (g/ml)": 25.8,
    "Porciones por envase": 12.015503875968992,
    "Grasa saturada (cal)": 14,
    "Otras grasas (cal)": 9,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 200,
    "Energía por porción (cal)": 82.89290322580645,
    "Energía por envase (cal)": 996,
    "Filename": "tortillas-harina",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Tortillas de harina integral",
    "Marca": "La Rosalía",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 71,
    "Tamaño (g/ml)": 255,
    "Porción (g/ml)": 25.5,
    "Porciones por envase": 10,
    "Grasa saturada (cal)": 14,
    "Otras grasas (cal)": 9,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 190,
    "Energía por porción (cal)": 71,
    "Energía por envase (cal)": 710,
    "Filename": "tortillas-integral",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Tortillas de maíz",
    "Marca": "Sumaiz",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 59,
    "Tamaño (g/ml)": 750,
    "Porción (g/ml)": 25,
    "Porciones por envase": 30,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 5,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 10,
    "Energía por porción (cal)": 59,
    "Energía por envase (cal)": 1770,
    "Filename": "tortillas-maiz",
    "Escala": 0.75,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Bebida isotónica",
    "Marca": "Thunderade",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 144,
    "Tamaño (g/ml)": 600,
    "Porción (g/ml)": 600,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 144,
    "Sodio (mg)": 280,
    "Energía por porción (cal)": 144,
    "Energía por envase (cal)": 144,
    "Filename": "bebida-isotonica",
    "Escala": 0.65,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Cerveza",
    "Marca": "",
    "Cantidad": 0,
    "Contenido energetico (kcal)": "",
    "Tamaño (g/ml)": "",
    "Porción (g/ml)": "",
    "Porciones por envase": "#DIV/0!",
    "Grasa saturada (cal)": "",
    "Otras grasas (cal)": "",
    "Azúcares (cal)": "",
    "Sodio (mg)": "",
    "Energía por porción (cal)": "#DIV/0!",
    "Energía por envase (cal)": "",
    "Filename": "cerveza",
    "Escala": "",
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Bebida energética",
    "Marca": "Blue horn",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 45,
    "Tamaño (g/ml)": 250,
    "Porción (g/ml)": 100,
    "Porciones por envase": 2.5,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 44,
    "Sodio (mg)": 40,
    "Energía por porción (cal)": 45,
    "Energía por envase (cal)": 223,
    "Filename": "bebida-energetica",
    "Escala": 0.9,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Brócoli",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 34,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0.35,
    "Otras grasas (cal)": 3,
    "Azúcares (cal)": 26.56,
    "Sodio (mg)": 33,
    "Energía por porción (cal)": 34,
    "Energía por envase (cal)": 34,
    "Filename": "brocoli",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Cebolla",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 42,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0.23,
    "Otras grasas (cal)": 0.49,
    "Azúcares (cal)": 40.44,
    "Sodio (mg)": 3,
    "Energía por porción (cal)": 42,
    "Energía por envase (cal)": 42,
    "Filename": "cebolla",
    "Escala": 1,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Elote",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 122,
    "Tamaño (g/ml)": 155,
    "Porción (g/ml)": 155,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 7.47,
    "Otras grasas (cal)": 1.35,
    "Azúcares (cal)": 117.52,
    "Sodio (mg)": 6,
    "Energía por porción (cal)": 122,
    "Energía por envase (cal)": 122,
    "Filename": "elote",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Espinaca",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 23,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0.39,
    "Azúcares (cal)": 0.42,
    "Sodio (mg)": 79,
    "Energía por porción (cal)": 23,
    "Energía por envase (cal)": 23,
    "Filename": "espinaca",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Mostaza",
    "Marca": "Enrique",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 0,
    "Tamaño (g/ml)": 368,
    "Porción (g/ml)": 12,
    "Porciones por envase": 30.666666666666668,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 144,
    "Energía por porción (cal)": 0,
    "Energía por envase (cal)": 0,
    "Filename": "mostaza",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": true,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Papa",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 80,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0.27,
    "Otras grasas (cal)": 0.72,
    "Azúcares (cal)": 73,
    "Sodio (mg)": 173,
    "Energía por porción (cal)": 80,
    "Energía por envase (cal)": 80,
    "Filename": "papa",
    "Escala": 1,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Pepino",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 14,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0.21,
    "Otras grasas (cal)": 1.05,
    "Azúcares (cal)": 11.6,
    "Sodio (mg)": 2,
    "Energía por porción (cal)": 14,
    "Energía por envase (cal)": 14,
    "Filename": "pepino",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Zanahoria",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 41,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0.33,
    "Otras grasas (cal)": 1.83,
    "Azúcares (cal)": 86.22,
    "Sodio (mg)": 69,
    "Energía por porción (cal)": 41,
    "Energía por envase (cal)": 41,
    "Filename": "zanahoria",
    "Escala": 1,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Calabacita",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 25,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0.4,
    "Otras grasas (cal)": 0.86,
    "Azúcares (cal)": 24.6,
    "Sodio (mg)": 2,
    "Energía por porción (cal)": 25,
    "Energía por envase (cal)": 25,
    "Filename": "calabacita",
    "Escala": 0.8,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Lechuga",
    "Marca": "Del campo",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 14,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0.16,
    "Otras grasas (cal)": 1.1,
    "Azúcares (cal)": 11.88,
    "Sodio (mg)": 10,
    "Energía por porción (cal)": 14,
    "Energía por envase (cal)": 14,
    "Filename": "lechuga",
    "Escala": 0.75,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Barra de granola-crujiente",
    "Marca": "Naturaleza",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 191,
    "Tamaño (g/ml)": 42,
    "Porción (g/ml)": 42,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 9,
    "Otras grasas (cal)": 55.8,
    "Azúcares (cal)": 108.4,
    "Sodio (mg)": 180,
    "Energía por porción (cal)": 191,
    "Energía por envase (cal)": 191,
    "Filename": "barra-granola-crujiente",
    "Escala": 0.7,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Barra de granola-almendras",
    "Marca": "Naturaleza",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 160,
    "Tamaño (g/ml)": 35,
    "Porción (g/ml)": 35,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 18,
    "Otras grasas (cal)": 45,
    "Azúcares (cal)": 88,
    "Sodio (mg)": 140,
    "Energía por porción (cal)": 160,
    "Energía por envase (cal)": 160,
    "Filename": "barra-granola-almendras",
    "Escala": 0.7,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Yogurt de fresa",
    "Marca": "LOL",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 188,
    "Tamaño (g/ml)": 240,
    "Porción (g/ml)": 240,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 25.2,
    "Otras grasas (cal)": 13.5,
    "Azúcares (cal)": 128.4,
    "Sodio (mg)": 72,
    "Energía por porción (cal)": 240,
    "Energía por envase (cal)": 240,
    "Filename": "yogurt-fresa",
    "Escala": 0.65,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Licuado de yogurt",
    "Marca": "LOL",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 187,
    "Tamaño (g/ml)": 240,
    "Porción (g/ml)": 240,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 25.2,
    "Otras grasas (cal)": 17.1,
    "Azúcares (cal)": 124,
    "Sodio (mg)": 76,
    "Energía por porción (cal)": 240,
    "Energía por envase (cal)": 240,
    "Filename": "licuado-yogurt",
    "Escala": 0.65,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Yogurt natural",
    "Marca": "Actua",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 158.3,
    "Tamaño (g/ml)": 225,
    "Porción (g/ml)": 225,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 20.7,
    "Otras grasas (cal)": 11.5,
    "Azúcares (cal)": 104,
    "Sodio (mg)": 98.2,
    "Energía por porción (cal)": 225,
    "Energía por envase (cal)": 225,
    "Filename": "yogurt-natural",
    "Escala": 0.65,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Arroz",
    "Marca": "Gerudo valley",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 282,
    "Tamaño (g/ml)": 1000,
    "Porción (g/ml)": 49,
    "Porciones por envase": 20.408163265306122,
    "Grasa saturada (cal)": 67,
    "Otras grasas (cal)": 44,
    "Azúcares (cal)": 152,
    "Sodio (mg)": 778,
    "Energía por porción (cal)": 281.897,
    "Energía por envase (cal)": 5753,
    "Filename": "arroz",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Pescado",
    "Marca": "Del mar",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 84,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 1.755,
    "Otras grasas (cal)": 6.48,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 81,
    "Energía por porción (cal)": 84,
    "Energía por envase (cal)": 84,
    "Filename": "pescado",
    "Escala": 0.65,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Camarón",
    "Marca": "Del mar",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 144,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 4,
    "Otras grasas (cal)": 17.15,
    "Azúcares (cal)": 4.96,
    "Sodio (mg)": 613,
    "Energía por porción (cal)": 144,
    "Energía por envase (cal)": 144,
    "Filename": "camaron",
    "Escala": 1.1,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Queso manchego",
    "Marca": "LOL",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 55,
    "Tamaño (g/ml)": 144,
    "Porción (g/ml)": 18,
    "Porciones por envase": 8,
    "Grasa saturada (cal)": 25,
    "Otras grasas (cal)": 14,
    "Azúcares (cal)": 5.2,
    "Sodio (mg)": 267,
    "Energía por porción (cal)": 55,
    "Energía por envase (cal)": 440,
    "Filename": "queso-manchego",
    "Escala": 0.8,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Queso americano",
    "Marca": "LOL",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 54,
    "Tamaño (g/ml)": 144,
    "Porción (g/ml)": 18,
    "Porciones por envase": 8,
    "Grasa saturada (cal)": 25,
    "Otras grasas (cal)": 14,
    "Azúcares (cal)": 4.4,
    "Sodio (mg)": 297,
    "Energía por porción (cal)": 54,
    "Energía por envase (cal)": 432,
    "Filename": "queso-americano",
    "Escala": 0.8,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Jamón de pavo",
    "Marca": "San juditas",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 11,
    "Tamaño (g/ml)": 250,
    "Porción (g/ml)": 11.4,
    "Porciones por envase": 21.929824561403507,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 1.8,
    "Azúcares (cal)": 0.8,
    "Sodio (mg)": 91,
    "Energía por porción (cal)": 10.989600000000001,
    "Energía por envase (cal)": 241,
    "Filename": "jamon-pavo",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Jamón de pierna",
    "Marca": "San juditas",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 26,
    "Tamaño (g/ml)": 250,
    "Porción (g/ml)": 10,
    "Porciones por envase": 25,
    "Grasa saturada (cal)": 1.8,
    "Otras grasas (cal)": 3.6,
    "Azúcares (cal)": 4.4,
    "Sodio (mg)": 150,
    "Energía por porción (cal)": 8.8,
    "Energía por envase (cal)": 220,
    "Filename": "jamon-pierna",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Botana saludable",
    "Marca": "Vegeta",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 63,
    "Tamaño (g/ml)": 28,
    "Porción (g/ml)": 28,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 9,
    "Otras grasas (cal)": 63,
    "Azúcares (cal)": 64,
    "Sodio (mg)": 230,
    "Energía por porción (cal)": 63,
    "Energía por envase (cal)": 63,
    "Filename": "botana-saludable",
    "Escala": 0.7,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Elote enlatado",
    "Marca": "La cosina",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 33,
    "Tamaño (g/ml)": 410,
    "Porción (g/ml)": 50,
    "Porciones por envase": 8.2,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 9,
    "Azúcares (cal)": 24,
    "Sodio (mg)": 136,
    "Energía por porción (cal)": 19.75609756097561,
    "Energía por envase (cal)": 162,
    "Filename": "elote-enlatado",
    "Escala": 0.75,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Fruta en almíbar",
    "Marca": "La cosina",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 40,
    "Tamaño (g/ml)": 850,
    "Porción (g/ml)": 50,
    "Porciones por envase": 17,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 160,
    "Sodio (mg)": 3,
    "Energía por porción (cal)": 40,
    "Energía por envase (cal)": 680,
    "Filename": "fruta-almibar",
    "Escala": 0.75,
    "ExCalorias": true,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Cajeta",
    "Marca": "Quemada",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 131,
    "Tamaño (g/ml)": 370,
    "Porción (g/ml)": 40,
    "Porciones por envase": 9.25,
    "Grasa saturada (cal)": 7.2,
    "Otras grasas (cal)": 1.8,
    "Azúcares (cal)": 113.6,
    "Sodio (mg)": 64,
    "Energía por porción (cal)": 254.48648648648648,
    "Energía por envase (cal)": 2354,
    "Filename": "cajeta",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Crema de cacahuate",
    "Marca": "Ali baba",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 196,
    "Tamaño (g/ml)": 340,
    "Porción (g/ml)": 32,
    "Porciones por envase": 10.625,
    "Grasa saturada (cal)": 18,
    "Otras grasas (cal)": 126,
    "Azúcares (cal)": 20,
    "Sodio (mg)": 130,
    "Energía por porción (cal)": 195.95294117647057,
    "Energía por envase (cal)": 2082,
    "Filename": "crema-cacahuate",
    "Escala": 0.6,
    "ExCalorias": true,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Té negro sabor durazno",
    "Marca": "Fusetec",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 48,
    "Tamaño (g/ml)": 600,
    "Porción (g/ml)": 200,
    "Porciones por envase": 3,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 48,
    "Sodio (mg)": 69,
    "Energía por porción (cal)": 48,
    "Energía por envase (cal)": 144,
    "Filename": "te-negro-durazno",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Mantequilla",
    "Marca": "LOL",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 36,
    "Tamaño (g/ml)": 90,
    "Porción (g/ml)": 5,
    "Porciones por envase": 18,
    "Grasa saturada (cal)": 23,
    "Otras grasas (cal)": 13,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 0,
    "Energía por porción (cal)": 36,
    "Energía por envase (cal)": 648,
    "Filename": "mantequilla",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Margarina",
    "Marca": "It's not butter...",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 27,
    "Tamaño (g/ml)": 454,
    "Porción (g/ml)": 5,
    "Porciones por envase": 90.8,
    "Grasa saturada (cal)": 8.1,
    "Otras grasas (cal)": 18.9,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 22,
    "Energía por porción (cal)": 20.088105726872246,
    "Energía por envase (cal)": 1824,
    "Filename": "margarina",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Mermelada",
    "Marca": "MacNoob",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 50,
    "Tamaño (g/ml)": 270,
    "Porción (g/ml)": 20,
    "Porciones por envase": 13.5,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 48,
    "Sodio (mg)": 0,
    "Energía por porción (cal)": 50,
    "Energía por envase (cal)": 675,
    "Filename": "mermelada",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": true,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Nieve de limón",
    "Marca": "Himalaya",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 57,
    "Tamaño (g/ml)": 666,
    "Porción (g/ml)": 50,
    "Porciones por envase": 13.32,
    "Grasa saturada (cal)": 0.9,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 55.2,
    "Sodio (mg)": 2,
    "Energía por porción (cal)": 56.914414414414416,
    "Energía por envase (cal)": 758.1,
    "Filename": "nieve-limon",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Nieve de vainilla",
    "Marca": "Himalaya",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 91,
    "Tamaño (g/ml)": 542,
    "Porción (g/ml)": 50,
    "Porciones por envase": 10.84,
    "Grasa saturada (cal)": 30.6,
    "Otras grasas (cal)": 3.6,
    "Azúcares (cal)": 52.4,
    "Sodio (mg)": 44,
    "Energía por porción (cal)": 90.99630996309963,
    "Energía por envase (cal)": 986.4,
    "Filename": "nieve-vainilla",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Nutella",
    "Marca": "Donatella",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 100,
    "Tamaño (g/ml)": 650,
    "Porción (g/ml)": 18,
    "Porciones por envase": 36.111111111111114,
    "Grasa saturada (cal)": 18,
    "Otras grasas (cal)": 46,
    "Azúcares (cal)": 40,
    "Sodio (mg)": 5,
    "Energía por porción (cal)": 99.99692307692307,
    "Energía por envase (cal)": 3611,
    "Filename": "nutella",
    "Escala": 0.6,
    "ExCalorias": true,
    "ExGrasasSat": true,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": true,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Pizza",
    "Marca": "Fuaa",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 125,
    "Tamaño (g/ml)": 216,
    "Porción (g/ml)": 54,
    "Porciones por envase": 4,
    "Grasa saturada (cal)": 18,
    "Otras grasas (cal)": 22,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 275,
    "Energía por porción (cal)": 125,
    "Energía por envase (cal)": 500,
    "Filename": "pizza",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Salmón",
    "Marca": "Del mar",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 146,
    "Tamaño (g/ml)": 100,
    "Porción (g/ml)": 100,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 11.34,
    "Otras grasas (cal)": 42.07,
    "Azúcares (cal)": 0,
    "Sodio (mg)": 46,
    "Energía por porción (cal)": 146,
    "Energía por envase (cal)": 146,
    "Filename": "salmon",
    "Escala": 0.65,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Spagetti",
    "Marca": "Non Capisco",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 345.5,
    "Tamaño (g/ml)": 500,
    "Porción (g/ml)": 100,
    "Porciones por envase": 5,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 4.5,
    "Azúcares (cal)": 284,
    "Sodio (mg)": 5,
    "Energía por porción (cal)": 345.5,
    "Energía por envase (cal)": 1727.5,
    "Filename": "spagetti",
    "Escala": 0.6,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Yogurt griego",
    "Marca": "Youplay",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 134,
    "Tamaño (g/ml)": 145,
    "Porción (g/ml)": 145,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 14,
    "Otras grasas (cal)": 9,
    "Azúcares (cal)": 69.7,
    "Sodio (mg)": 116,
    "Energía por porción (cal)": 134,
    "Energía por envase (cal)": 134,
    "Filename": "yogurt-griego",
    "Escala": 0.8,
    "ExCalorias": false,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": false,
    "ContEdulcorantes": false,
    "ContCafeina": false
  },
  {
    "Producto": "Refresco",
    "Marca": "Rock-Cola",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 60,
    "Tamaño (g/ml)": 600,
    "Porción (g/ml)": 600,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 252,
    "Sodio (mg)": 60,
    "Energía por porción (cal)": 252,
    "Energía por envase (cal)": 252,
    "Filename": "refresco",
    "Escala": 0.55,
    "ExCalorias": true,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": true,
    "ContEdulcorantes": true,
    "ContCafeina": false
  },
  {
    "Producto": "Refresco",
    "Marca": "Rock-Cola",
    "Cantidad": 0,
    "Contenido energetico (kcal)": 60,
    "Tamaño (g/ml)": 600,
    "Porción (g/ml)": 600,
    "Porciones por envase": 1,
    "Grasa saturada (cal)": 0,
    "Otras grasas (cal)": 0,
    "Azúcares (cal)": 252,
    "Sodio (mg)": 60,
    "Energía por porción (cal)": 252,
    "Energía por envase (cal)": 252,
    "Filename": "refresco",
    "Escala": 0.55,
    "ExCalorias": true,
    "ExGrasasSat": false,
    "ExGrasasTrans": false,
    "ExSodio": false,
    "ExAzucares": true,
    "ContEdulcorantes": true,
    "ContCafeina": false
  }
]